name: Deploy MagicCap update
on:
  push:
    branches:
      - stable
      - beta
      - alpha

jobs:
  linux-build:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17"
      - name: Run the build script
        run: make linux-ci

  darwin-build:
    needs: linux-build
